M48
; DRILL file KiCad 10.0.2 date 2026-07-03T19:17:24
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-03T19:17:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X152.75Y-87.0
X152.75Y-98.0
X205.75Y-88.5
X205.75Y-113.5
T2
X152.75Y-79.75
X152.75Y-137.75
M30
