set(STATE_MACHINE_LIBRARY_INC 
    ${CMAKE_CURRENT_SOURCE_DIR}/Inc 
)

set(STATE_MACHINE_LIBRARY_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/state_machine.cpp
)

add_library(STATE_MACHINE_LIBRARY INTERFACE)
target_include_directories(STATE_MACHINE_LIBRARY INTERFACE ${STATE_MACHINE_LIBRARY_INC})
target_sources(STATE_MACHINE_LIBRARY PUBLIC ${STATE_MACHINE_LIBRARY_SRC})