set(WRAPPER_LIBRARY_INC 
    ${CMAKE_CURRENT_SOURCE_DIR}/Inc 
)

set(WRAPPER_LIBRARY_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/fdcan.cpp
)

add_library(WRAPPER_LIBRARY INTERFACE)
# target_include_directories(PUTM_EV_CAN_LIBRARY INTERFACE ${MX_Include_Dirs})
target_include_directories(WRAPPER_LIBRARY INTERFACE ${WRAPPER_LIBRARY_INC})
target_sources(WRAPPER_LIBRARY PUBLIC ${WRAPPER_LIBRARY_SRC})