set(ERROR_CHECKER_LIBRARY_INC 
    ${CMAKE_CURRENT_SOURCE_DIR}/Inc 
)

set(ERROR_CHECKER_LIBRARY_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/Src/error_checker.cpp
)

add_library(ERROR_CHECKER_LIBRARY INTERFACE)
target_include_directories(ERROR_CHECKER_LIBRARY INTERFACE ${ERROR_CHECKER_LIBRARY_INC})
target_sources(ERROR_CHECKER_LIBRARY INTERFACE ${ERROR_CHECKER_LIBRARY_SRC})